---
- name: Install and Start nginx and Stop nginx
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    apt:
     name: nginx
     state: present
  - name: Start nginx
    service:
      name: nginx
      state: started
  - name: Stop nginx
    service: 
     name: nginx
     state: stopped
